name: Trigger auto deployment for waracle-hotel-booking

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/waracle-hotel-booking-AutoDeployTrigger-d7d5fbd0-5152-44af-aa06-2050b3a11e1f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WARACLEHOTELBOOKING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WARACLEHOTELBOOKING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WARACLEHOTELBOOKING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.WARACLEHOTELBOOKING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WARACLEHOTELBOOKING_REGISTRY_PASSWORD }}
          containerAppName: waracle-hotel-booking
          resourceGroup: tech-challenge
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


